### PR TITLE
fix: Adding multiple CNAME records concurrently

### PR DESCRIPTION
**Pull request by jlilja**
* Adds a mutex lock on the delete for CNAME 
* Adds tests to verify 
* Adds documentation and examples of data source examples folder.

### CODE REVIEW

**Comment by jlilja** [comment]
closes #68

**Comment by jlilja** [comment]
Looks like something is broken in the nightly build. But I don't believe that its something that should be a stopper for this to be merged. If it makes its way into stable then its worth taking a look at.

**Comment by ryanwholey** [comment]
maybe we should ignore the nightly version for now?

**Comment by ryanwholey** [comment]
It would be nice to make sure the tests are running against the rest of the stable versions

**Comment by jlilja** [comment]
There we go! Looks like this only affects the nightly build :slightly_smiling_face:

**Review by ryanwholey — APPROVED** [review]
thanks for the update. I think I'll remove nightly builds from the PR checks, maybe we can have that be a scheduled one that runs on a cadence so it doesn't affect the PR statuses

**Pull request merged**
